# Generated by Django 3.2.19 on 2023-06-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_filter',
            new_name='post_filter',
        ),
    ]
